banking_system_project/banking_system_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'banking_system_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('bank/', views.bank, name='bank'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('<int:pk>/',views.single_customer,name='single_customer'),
]

banking_system_project/banking_system_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('banking_system_app.urls')),
    path('accounts/', include('login_app.urls')),
]

banking_system_project/login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
    path('delete_account', views.delete_account, name='delete_account'),
]

banking_system_project/banking_system_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=250)

    @classmethod
    def create(cls, user, text):
        account = cls()
        account.user = user
        account.text = text
        account.save()
    
    def __str__(self):
        return f"{self.text}"

class UserProfile (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.IntegerField(default = 0)
    membership = models.CharField(max_length = 50, default = None)
    role = models.CharField(max_length = 50, default = None)

    @classmethod
    def create(cls, user):
        userprofile = cls()
        userprofile.user = user
        userprofile.save() 

    def __str__(self):
        return f"{self.user}"


class Loan (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField(default = 0)
    loantype = models.CharField(max_length = 50, default = None)

    @classmethod
    def create(cls, user):
        loan = cls()
        loan.user = user
        loan.save() 

    def __str__(self):
        return f"{self.user}"

class Transaction (models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.IntegerField(default = 0)
    balance = models.IntegerField(default = 0)
    date = models.DateField()
    transactiontype = models.CharField(max_length = 50, default = None)

    @classmethod
    def create(cls, account):
        transaction = cls()
        transaction.account = account
        transaction.save() 

    def __str__(self):
        return f"{self.account}"

banking_system_project/login_app/models.py
from django.db import models

from django.contrib.auth.models import User
from secrets import token_urlsafe

class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    secret = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

def __str__(self):
    return f'{self.user} - {self.created_timestamp}'
    

banking_system_project/banking_system_app/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.contrib.auth.models import User
from .models import Account
from django.http import HttpResponseRedirect
from . import models
from .models import UserProfile
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    if request.method == 'POST':
        Account.create(request.user, request.POST['text'])

    accounts = Account.objects.all().filter(user=request.user)
    context = {
        'accounts': accounts,
    }
    return render (request, 'banking_system_app/index.html', context)

@login_required
def bank(request):
    if request.method == "POST":
        text = request.POST["text"]
        user = User()
        user.username = username
        user.save()

    users = User.objects.all()
    context = {
        'users' : users,
    }
    return render (request, 'banking_system_app/bank.html', context)

@login_required
def sign_up(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']

        phone = request.POST['phone']
        role = request.POST['role']
        membership = request.POST['membership']

        if password == confirm_password:
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            if user:
                userprofile = UserProfile()
                userprofile.user = user
                userprofile.phone = phone
                userprofile.role = role
                userprofile.membership = membership
                userprofile.save()
                return HttpResponseRedirect(reverse('banking_system_app:bank'))
            else:
                context = {'error': 'Could not create user - try something else'}
        else:
            context ={'error': 'Passwords do not match.'}
    return render(request, 'banking_system_app/sign_up.html', context)

@login_required
def single_customer(request, pk):
    user = User.objects.get(pk=pk)
    context = {
        'user': user,
    }
    return render(request, 'banking_system_app/single_customer.html', context)

banking_system_project/login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from . import models
# import django_rq
# from . messaging import email_message

# Create your views here.
def login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('banking_system_app:index'))
        else:
            context = {'error': 'Bad username or password.'}
    return render(request, 'login_app/login.html', context)

def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reserve('login_app:login'))

def password_reset(request):
    context = {}

    if request.method == "POST":
        email = request.POST['email']
        user = User.objects.get(email=email)
        reset_request = models.PasswordResetRequest()
        reset_request.user = user
        reset_request.save()
        url = reverse('login_app:password_reset_secret', args=[f'{reset_request.secret}'])
        url = f'{request.scheme}://{request.META["HTTP_HOST"]}{url}'
        print(url)
        context ={'message': 'Please click the link in the email we send you'}
        # django_rq.enqueue(email_message, {'email_receiver': email, 'reset_link': url})

    return render(request, 'login_app/password_reset.html', context)

def password_reset_secret(request, secret):
    context = {'secret': secret}
    return render(request, 'login_app/password_reset_form.html', context)

def password_reset_form(request):
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']
    secret = request.POST['secret']

    user = User.objects.get(email=email)
    reset_request = models.PasswordResetRequest.objects.get(user=user, secret=secret)
    if password == confirm_password:
        user.set_password(password)
        user.save()
        reset_request.save()
        return HttpResponseRedirect(reverse('login_app:login'))
    context = {'error': 'Something went wrong...'}
    return render (request, 'login_app/password_reset_form.html', context)
   

def delete_account(request):
    pass

banking_system_project/banking_system_app/templates/banking_system_app/bank.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'banking_system_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a class="active" href="{% url 'banking_system_app:bank' %}">Home</a></li>
            <li><a href="{% url 'banking_system_app:sign_up' %}">Register new customer</a></li>
        </ul>
    </nav>

    <h1>Hello, {{ user.username }}</h1>
    <hr>

    <p>Here are your customers:</p>
    <ul>
        {% for user in users  %}
            <li><a href="/{{user.pk}}">{{ user.username }}</a></li>
        {% endfor %}
    </ul>
    
</body>
</html>

banking_system_project/banking_system_app/templates/banking_system_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Banking system</title>
</head>
<body>
    <h1>Hi {{ user.username }}</h1>
    <p>Here are your accounts:</p>
    <ul>
    {% for account in accounts  %}
        <li>{{ account.text }}</li>
    {% endfor %} 
    </ul>

    <hr />
    <form action="." method="POST">
       {% csrf_token %}
       <input type="text" name="text" placeholder="Give the account a name" />
       <button>Create a new account</button>
    </form>
</body>
</html>

banking_system_project/banking_system_app/templates/banking_system_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign up</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'banking_system_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'banking_system_app:bank' %}">Home</a></li>
            <li><a class="active" href="{% url 'banking_system_app:sign_up' %}">Register new customer</a></li>
        </ul>
    </nav>
    <h1>Sign up</h1>
    <hr>

    <form action="{% url 'banking_system_app:sign_up' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="text" name="firstname" placeholder="First Name">
        <input type="text" name="lastname" placeholder="Last Name">
        <input type="password" name="password" placeholder="password">
        <input type="password" name="confirm_password" placeholder="Confirm Password">
        <input type="email" name="email" placeholder="email">

        <input type="tel" name="phone" placeholder="Phone">
        <br>
        <select name="role">
            <option value="customer">Customer</option>
            <option value="employee">Bank employee</option>
        </select>
        <br>
        <select name="membership">
            <option value="basic">Basic</option>
            <option value="silver">Silver</option>
            <option value="gold">Gold</option>
        </select>
        
        <br>
        <input type="submit" value="Create customer">
    </form>
    
</body>
</html>

banking_system_project/banking_system_app/templates/banking_system_app/single_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'banking_system_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'banking_system_app:bank' %}">Home</a></li>
            <li><a href="{% url 'banking_system_app:sign_up' %}">Register new customer</a></li>
        </ul>
    </nav>

    <h2>{{ user.userprofile.role }}: {{ user.first_name }} {{ user.last_name }}</h2>
    <div class="basic_info">
        <p>Phone number: {{ user.userprofile.phone }}</p>
        <p>Email Address: {{ user.email }}</p>
        <p>Membership: {{ user.userprofile.membership }}</p>
    </div>
    <hr>

    <div>
        <h3>Accounts associated with this {{ user.userprofile.role }}</h3>
        <ul>
        {% for account in accounts  %}
            <li>{{user.account.text}}</li>
        {% endfor %}
        </ul>
    </div>

</body>
</html>

banking_system_project/login_app/templates/login_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
 
    <a href="{% url 'login_app:password_reset' %}">Reset password</a>
    <hr>

    <form action="{% url 'login_app:login' %}" method="POST">
        {% csrf_token %} <!-- Prevents x-site scripting. Good security measure. -->
        <input type="text" name="username" placeholder="Username">
        <br>
        <input type="password" name="password" placeholder="password">
        <br>
        <input type="submit" value="Login">
    </form>
    <hr>
    {% if error %}<p style="color:red;">{{ error }}</p>{% endif %}
    
</body>
</html>

banking_system_project/login_app/templates/login_app/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
</head>
<body>
    <h1>Password Reset</h1>
    <a href="{% url 'login_app:login' %}">Log In</a>
    <hr>
    <form action="{% url 'login_app:password_reset' %}" method="POST">
        {% csrf_token %}
        <input type="email" name="email" placeholder="email">
        <input type="submit" value="Reset password">
    </form>
    <hr>
    {% if message %}{{ message }}{% endif %}
</body>
</html>

banking_system_project/login_app/templates/login_app/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create new password</title>
</head>
<body>
    <h1>Please set new password</h1>
    <hr>
    <form action="{% url 'login_app:password_reset_form' %}" method="POST">
        {% csrf_token %}
        <input type="email" name="email" placeholder="Email">
        <input type="password" name="password" placeholder="password">
        <input type="password" name="confirm_password" placeholder="Confirm password">
        <input type="hidden" name="secret" value="{{ secret }}">
        <input type="submit" value="Create new password">
    </form>
    <hr>
    {% if error %}{{ error }}{% endif %}
    
</body>
</html>